export const META = {
  title: 'Next App',
  description: 'Generated by create next app'
}

export const MESSAGE = {
  success: 'This email was sent successfully. I will get back to you as soon as possible.',
  error: 'The email could not be sent correctly. You can send an email directly to the "thuranaing.ucsm@gmail.com" email address.'
}
